---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Pull a Docker Image
    docker_image:
       name: django
       tag: latest
       source: pull
    register: z

  - name: Checking Pull status
    debug:
      var: z

  - name: Copying the code to the container
    git:
      repo: git@github.com:saliouseck2009/projet-test-awx.git
      dest: /home/vagrant
  -name: Install depence
  - pip:
      name: django
      executable: pip-3

  - name: Lunching the container
    when: z.failed == false
    docker_container:
      name: django application
      image: django
      state: started
      exposed_ports:
        - "8000"
      ports:
        - "8000:8000"


    
