name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: http://3e5fa5cf4331.ngrok.io:80/api/v2/job_templates/12/github/
        webhook_secret: UPN1EgQqUuCLNZXOxa2qW4lAW4mHdxiOeVpcJcsvwMgVVTWB4u
    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: xoxb-1546538880519-1561156860085-gAmqVGAXODi0fi5V5XM67tY0
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: app-alerts
        status: FAILED
        color: danger
    
